### ISSUE TITLE
Add support for pprof for CSI sidecars

### ISSUE THREAD

**Issue by Fricounet** [kubernetes-csi/csi-lib-utils#137]
Currently, some of the CSI sidecars support pprof profliing (like the [azuredisk-csi-driver](https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1657), the [secrets-store-csi-driver](https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/396/files) or the [node-driver-registrar](https://github.com/kubernetes-csi/node-driver-registrar/pull/171/files) but not all. I believe it could be useful to add this option on all CSI components and this repo seems like a good place to do it.

It could probably go in the [metrics.go](https://github.com/kubernetes-csi/csi-lib-utils/blob/master/metrics/metrics.go#L101) file in the `CSIMetricsManager` interface with a `RegisterPprofToServer` function that would register the pprof handlers.

What do you folks think about it? I would be happy to contribute this (and the implementation in the CSI sidecars) if that is something folks are willing to see 😄

**Comment by xing-yang** [comment]
Hi @Fricounet , we discussed about this and agreed this is useful.  Please go ahead and submit PRs.  Thanks!

**Comment by jsafrane** [comment]
I like it, but please make it configurable via `--enable-pprof` or something similar. Some CSI drivers need to use host network, i.e. the port for metrics + pprof will be open on the node. And at the same time, people may not like exposing CPU profiles, heap data and whatnot publicly on that node.
