### ISSUE TITLE
Add otel trace instrumentation on gRPC calls

### ISSUE THREAD

**Issue by Fricounet** [kubernetes-csi/csi-lib-utils#139]
I'm proposing to add some basic tracing instrumentation of the gRPC calls made by the CSI clients using the code in [connection.go](https://github.com/kubernetes-csi/csi-lib-utils/blob/master/connection/connection.go) to connect to the CSI driver. 
The feature simply consists in adding the [otelgrpc.UnaryClientInterceptor()](https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc#UnaryClientInterceptor) to the existing [ChainUnaryInterceptor](https://github.com/kubernetes-csi/csi-lib-utils/blob/master/connection/connection.go#L121). This is enough to create traces for all gRPC calls and they can be easily exported by the client.

I think it can be done by creating a new `ConnectWithGrpcInterceptor` function that will call the `connect` function with the added interceptor as a `DialOption`. This way the feature will be opt-in for the users.

I can contribute it (and the implementation in the CSI components) if it is something the community wants to see. I already implemented something similar on the [azuredisk-csi-driver](https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1912) and plan to do the same for aws and gcp drivers.

**Comment by Fricounet** [comment]
@jsafrane here is an example of the information gathered on a trace by the gRPC interceptor.
I collapsed the `os` and `process` fields because they are just some metadata that are not linked to the gRPC interceptor itself. Here, the relevant field for the interceptor are `event` which is the gRPC message itself and `rpc` which indicates which method was called.
I never noticed any confidential information leaking this way but if you have an example of a CSI components where you think it might happen, I'd be glad to test it on my side to check if there is any leakage.

![image](https://github.com/kubernetes-csi/csi-lib-utils/assets/57704682/b95960a8-21e8-4836-b883-21dcc4f09c70)

**Comment by jsafrane** [comment]
Thanks for the example, it looks good - it has just the method name and not secrets that are in method arguments.
