### ISSUE TITLE
Common leader election library

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/csi-lib-utils#15]
Let's standardize on using the [Lease](https://github.com/kubernetes/kubernetes/pull/70778) mechanism for all the sidecars, and try to have common arguments too.

cc @wongma7 @xing-yang

**Comment by jsafrane** [comment]
I am 100% for standardizing leader election, there is just one glitch: it will pull lot of Kubernetes dependencies into this library. It will complicate rebases and releases - with new Kubernetes, one needs to update csi-lib-utils and external-provisioner-lib, wait until they release a new version and then bump their versions in all sidecars that use it. Is there a way how to do it better / faster?

**Comment by andrewsykim** [comment]
> It will complicate rebases and releases - with new Kubernetes, one needs to update csi-lib-utils and external-provisioner-lib, wait until they release a new version and then bump their versions in all sidecars that use it. Is there a way how to do it better / faster?

Can we go back to mono repos? 😆

**Comment by xing-yang** [comment]
Just read Jan's comments.  I see what he meant.  Right now this lib does not have dependency on kubernetes.  Once we add this function in here, this lib will have dependencies on kubernetes.  We need to sync up kubernetes versions all the way up to all sidecar containers that use this lib.  I don't know if there's a better way.  One alternative is to leave it to each sidecar container to implement this, but then we don't have a common lib to use.

**Comment by msau42** [comment]
/close
Done in #21 

We can hopefully have better dependency management with go modules.
