### ISSUE TITLE
configure prow presubmit jobs

### ISSUE THREAD

**Issue by pohly** [kubernetes-csi/csi-lib-utils#2]
We should run `make test` or some equivalent of it before each PR merge. As this is a Kubernetes repo and we already use prow for merging, we should also use prow for testing.

**Comment by pohly** [comment]
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/config.yaml and the corresponding https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/tree/master/test show how this can be done.

@saad-ali, @msau42 shall we create a `test-infra/config/jobs/sig-storage` and start adding job configs for the kubernetes-csi repos there, starting with `csi-lib-utils`?

I can work on that.

**Comment by msau42** [comment]
Yes this sounds like a great idea
